//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnonNerd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public post()
        {
            this.comment = new HashSet<comment>();
        }
    
        public int idPosts { get; set; }
        public string Online { get; set; }
        public System.DateTime Date { get; set; }
        public string Title { get; set; }
        public string Mainpic { get; set; }
        public string Intro { get; set; }
        public int Writer { get; set; }
        public Nullable<int> Views { get; set; }
        public string Tags { get; set; }
        public string Pic1 { get; set; }
        public string Vid1 { get; set; }
        public string Subtitle { get; set; }
        public string Text2 { get; set; }
        public string Pic2 { get; set; }
        public string Vid2 { get; set; }
        public string Subtitle2 { get; set; }
        public string Text3 { get; set; }
        public string Pic3 { get; set; }
        public string Vid3 { get; set; }
        public string Subtitle3 { get; set; }
        public string Text4 { get; set; }
        public string Pic4 { get; set; }
        public string Vid4 { get; set; }
        public string Text5 { get; set; }
        public string Pic5 { get; set; }
        public string Vid5 { get; set; }
        public string End { get; set; }
        public string Link1 { get; set; }
        public string Link2 { get; set; }
        public string Link3 { get; set; }
        public string Link4 { get; set; }
        public string Link5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comment { get; set; }
        public virtual writer writer1 { get; set; }
    }
}
