//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnonNerd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subcomment
    {
        public int idsubcomment { get; set; }
        public string Content { get; set; }
        public System.DateTime Date { get; set; }
        public int Writer { get; set; }
        public Nullable<int> Maincomment { get; set; }
    
        public virtual comment comment { get; set; }
    }
}
