//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace personal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intrests
    {
        public int Idintrest { get; set; }
        public int IdUser { get; set; }
        public string intrest { get; set; }
        public Nullable<int> importance { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
