//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace personal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matches
    {
        public int idMatch { get; set; }
        public int UseridMatch { get; set; }
        public int idUser { get; set; }
        public string Matchintrest { get; set; }
        public Nullable<int> Matchnumbers { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
